In [22]:
import pandas as pd
import os

In [52]:
#Read vine tabe data as datafram
vine_data="vine_data.csv"
df=pd.read_csv(vine_data)
df.head()

review_id            2302401
star_rating          2302392
helpful_votes        2302392
total_votes          2302392
vine                 2302392
verified_purchase    2302392
dtype: int64

In [24]:
#total_votes greater than or equql to 20 
total_votes_df=df.loc[(df["total_votes"])>=20,:]
total_votes_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
47,RFVL9IHYEMEO5,5.0,31.0,32.0,N,Y
76,R1VUIQLS5STWJ4,5.0,19.0,20.0,N,Y
149,R2FP3U4NHNFNL2,5.0,25.0,29.0,N,Y
243,R1UUK1977O38MU,5.0,31.0,31.0,N,Y
971,R3OLJ2RHCTY952,5.0,28.0,28.0,N,Y
...,...,...,...,...,...,...
2302319,R2VX8YPKDJ60MF,5.0,26.0,28.0,N,Y
2302359,R1ZDSX9W10673K,2.0,31.0,32.0,N,N
2302365,R2MC91QOWBHABQ,1.0,39.0,51.0,N,Y
2302366,R2MOPKX5FVJKOH,5.0,76.0,76.0,N,Y
2302377,R1E5J6G96EHTTX,5.0,63.0,70.0,N,N

In [26]:
#helpful_votes divided by total_votes is equal to or greater than 50%
helpful_votes_df=total_votes_df.loc[(total_votes_df["helpful_votes"])/(total_votes_df["total_votes"])*100>=50,:]
helpful_votes_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
47,RFVL9IHYEMEO5,5.0,31.0,32.0,N,Y
76,R1VUIQLS5STWJ4,5.0,19.0,20.0,N,Y
149,R2FP3U4NHNFNL2,5.0,25.0,29.0,N,Y
243,R1UUK1977O38MU,5.0,31.0,31.0,N,Y
971,R3OLJ2RHCTY952,5.0,28.0,28.0,N,Y
...,...,...,...,...,...,...
2302319,R2VX8YPKDJ60MF,5.0,26.0,28.0,N,Y
2302359,R1ZDSX9W10673K,2.0,31.0,32.0,N,N
2302365,R2MC91QOWBHABQ,1.0,39.0,51.0,N,Y
2302366,R2MOPKX5FVJKOH,5.0,76.0,76.0,N,Y
2302377,R1E5J6G96EHTTX,5.0,63.0,70.0,N,N

In [27]:
#Retrieve rows where vine program is paid(==Y)
vine_paid=helpful_votes_df.loc[(helpful_votes_df["vine"])=="Y",:]
vine_paid

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
60130,R3KPC0NBUDASX3,5.0,25.0,25.0,Y,N
108010,R3KDMPS96IJ10R,2.0,15.0,21.0,Y,N
116727,R1XWEI58A7VKLB,5.0,123.0,128.0,Y,N
138506,R1CJWM6CMWKSA1,4.0,31.0,33.0,Y,N
156916,R39I3FUDBKZM3Y,5.0,34.0,38.0,Y,N
...,...,...,...,...,...,...
2213101,R1GZM4X209D0AV,3.0,22.0,29.0,Y,N
2214965,R1ZHK9TOJHLYZP,5.0,53.0,54.0,Y,N
2277167,R3DRUOHZ2JAT58,5.0,27.0,29.0,Y,N
2294673,RGSTYZNOSD07J,5.0,30.0,35.0,Y,N
2302271,R2L0K6QATISXVY,3.0,47.0,59.0,Y,N

In [28]:
#Retrieve rows where vine program is unpaid(==N)
vine_unpaid=helpful_votes_df.loc[(helpful_votes_df["vine"])=="N",:]
vine_unpaid

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
47,RFVL9IHYEMEO5,5.0,31.0,32.0,N,Y
76,R1VUIQLS5STWJ4,5.0,19.0,20.0,N,Y
149,R2FP3U4NHNFNL2,5.0,25.0,29.0,N,Y
243,R1UUK1977O38MU,5.0,31.0,31.0,N,Y
971,R3OLJ2RHCTY952,5.0,28.0,28.0,N,Y
...,...,...,...,...,...,...
2302319,R2VX8YPKDJ60MF,5.0,26.0,28.0,N,Y
2302359,R1ZDSX9W10673K,2.0,31.0,32.0,N,N
2302365,R2MC91QOWBHABQ,1.0,39.0,51.0,N,Y
2302366,R2MOPKX5FVJKOH,5.0,76.0,76.0,N,Y
2302377,R1E5J6G96EHTTX,5.0,63.0,70.0,N,N

In [60]:
#Count paid vine program reviews where start rating is 5
vine_paid_review_count=vine_paid.loc[vine_paid["star_rating"]==5.0].count()["review_id"]
vine_paid_review_count

56

In [62]:
#Count paid vine program reviews
vine_paid_total_reviews=vine_paid["review_id"].count()
vine_paid_total_reviews

107

In [65]:
#Calculate percentage of paid 5-start rating vine program
vine_paid_five_star_percent=(vine_paid_review_count/vine_paid_total_reviews)*100
round(vine_paid_five_star_percent,2)

52.34

In [66]:
#Count unpaid vine program reviews where start rating is 5
vine_unpaid_review_count=vine_unpaid.loc[vine_unpaid["star_rating"]==5.0].count()["review_id"]
vine_unpaid_review_count

21005

In [67]:
#Count unpaid vine program reviews
vine_unpaid_total_reviews=vine_unpaid["review_id"].count()
vine_unpaid_total_reviews

39869

In [68]:
#Calculate percentage of unpaid 5-start rating vine program
vine_unpaid_five_star_percent=(vine_unpaid_review_count/vine_unpaid_total_reviews)*100
round(vine_unpaid_five_star_percent,2)

52.69

# Additional code to check the verified_purchase in unpaid reviews

In [51]:
unpaid_verified_df=vine_unpaid_review_count=vine_unpaid.loc[(vine_unpaid["star_rating"]==5.0) & \
                                                            (vine_unpaid["verified_purchase"]=="N")].count()["review_id"]
unpaid_verified_df

6084